# /qompassai/blaze-ts.nvim/pixi.toml
# ------------------------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

[project]
name = "blaze-ts_nvim"
version = "0.1.0"
description = "A 🔥 TreeSitter"
authors = ["Matt A. Porter<map@qompass.ai> "]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
build = "cargo zigbuild --release"
install = "cargo install --path . --locked"
test = "cargo test"
test-all = "cargo test --all-features"
lint = "pre-commit run --all"
docs = { cmd = "mkdocs serve" }
build-docs = { cmd = "mkdocs build --strict" }

[dependencies]
pre-commit = "~=3.3.0"

rust = "~=1.73.0"
openssl = "3.*"
pkg-config = "0.29.*"
git = "2.42.0.*"

mkdocs = "1.5.3.*"
mkdocs-material = "9.4.4.*"
pillow = ">=9.4.0.*"
cairosvg = "2.7.1.*"

[target.linux-64.dependencies]
compilers = ">=1.6.0"
